### ISSUE TITLE
Request of Info

### ISSUE THREAD

**Issue by Dario-Mantegazza** [RenaKunisaki/mariokart64#3]
Hi,
I'm doing a Reinforcement Learning Project for an University course.
I'm trying to find where (in the game memory) the player position is stored.
I'll use this value(hoping that could be normalized to represent a lap) as the reward function of the Agent.
I'm using mupen64plus on MacOs or Ubuntu.
Thank you

**Comment by abney317** [comment]
By position do you mean x,y,z coordinates of the player or like 1st-8th place in the race?

**Comment by Dario-Mantegazza** [comment]
Hi,
With position I mean the relative position of the player along the course lenght.
I think that something similar must be present otherwise I don't know how they can represent the player on the map or on "square" visualisation of the map (shown in the figure attached).
![2017-11-30 11 35 25](https://user-images.githubusercontent.com/24303917/33426584-9f096214-d5c2-11e7-85ef-f9fa2838ff84.jpg)
I'll try to explain better what I mean: at the start of the race the player is at the 0% of the length of the track, at half lap is at 50% and when is almost over the finish line is at 99%.
Even the value for the lap that is currently run (e.g.2nd lap of 3) could do the trick, not quite as the "run distance" written above but it could work.
Also we have adapted our project to even run on Windows with the emulator BizHawk.

I hope that I explained better what I need.
Thank you very much for your help

UPDATE: I've just realised that in some way the game is detecting if a player is going in the wrong direction; even this "flag" could be useful.
In general I need something that tells me that if the player is going in the right direction or not.
Little explain: in Reinforcement Learning you have to find a way to reward the actions of the Agent (aka the machine learning program that controls the game). In the Mario Kart case I thought to reward the Agent if it goes in right direction.

**Comment by RenaKunisaki** [comment]
RAM address 0x80163288 (N64 memory space, 32-bit integer) should be what you're after. I'm not sure how to determine what 100% is other than checking it in each course.

**Comment by Dario-Mantegazza** [comment]
Thank you!
